highlighter: rouge
permalink: pretty
markdown: kramdown

title: Fortran Programming Language
description: "Fortran Programming Language"

news:
    name: Fortran Newsletter
    authors: Fortran Community
    url: /news
    feed: /news.xml

url: "https://fortran-lang.org"

plugins:

exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - vendor/
